# Generated by Django 5.1.7 on 2026-06-06 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='省份名称')),
                ('capital', models.CharField(default='', max_length=20, verbose_name='省会/首府')),
                ('abbr', models.CharField(default='', max_length=4, verbose_name='简称')),
                ('feature', models.CharField(blank=True, default='', max_length=100, verbose_name='特色')),
                ('emoji', models.CharField(blank=True, default='', max_length=4, verbose_name='Emoji')),
                ('fun_fact', models.TextField(blank=True, default='', verbose_name='趣味知识')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('image', models.CharField(blank=True, default='', max_length=200, verbose_name='主图路径')),
                ('visited_count', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'db_table': 'provinces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='区域名称')),
            ],
            options={
                'verbose_name': '区域',
                'verbose_name_plural': '区域',
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('capital', '省会'), ('abbr', '简称'), ('feature', '特色')], max_length=20, verbose_name='题目类型')),
                ('question_text', models.CharField(max_length=200, verbose_name='题目内容')),
                ('correct_answer', models.CharField(max_length=50, verbose_name='正确答案')),
                ('option_a', models.CharField(max_length=50, verbose_name='选项A')),
                ('option_b', models.CharField(max_length=50, verbose_name='选项B')),
                ('option_c', models.CharField(max_length=50, verbose_name='选项C')),
                ('option_d', models.CharField(max_length=50, verbose_name='选项D')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.province', verbose_name='关联省份')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'quiz_questions',
            },
        ),
        migrations.AddField(
            model_name='province',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces', to='api.region', verbose_name='所属区域'),
        ),
    ]
